CREATE TABLE tracked_assets (
    id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    interval SMALLINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);